export const types = {
    ERROR_GET_PRODUCTS: "ERROR_GET_PRODUCTS",
    FINISH_GET_PRODUCTS: "FINISH_GET_PRODUCTS",
    START_GET_PRODUCTS: "START_GET_PRODUCTS",
    OPEN_DIALOG: "OPEN_DIALOG",
    CLOSE_DIALOG: "CLOSE_DIALOG",
    SET_DIALOG_STATE: "SET_DIALOG_STATE",
    PUSH_TO_SHEET: "PUSH_TO_SHEET",
    POP_FROM_SHEET: "POP_FROM_SHEET",
    ERROR_CALCULATE: "ERROR_CALCULATE",
    FINISH_CALCULATE: "FINISH_CALCULATE",
    START_CALCULATE: "START_CALCULATE",
    RESET_CALC: "RESET_CALC",
};
